# Generated by Django 5.0.7 on 2025-10-30 22:17

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='filters',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
