# Generated by Django 5.0.7 on 2025-10-29 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_source', models.CharField(default='gps', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='locations.apartment')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_profile', models.CharField(blank=True, max_length=255)),
                ('services_current', models.JSONField(blank=True, default=list)),
                ('provider_satisfaction', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('SAT', 'Satisfied'), ('UNSAT', 'Unsatisfied')], max_length=5)),
                ('interested_services', models.JSONField(blank=True, default=list)),
                ('best_call_time', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('fair_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='surveys.visit')),
            ],
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['apartment', 'visited_at'], name='surveys_vis_apartme_0f7451_idx'),
        ),
    ]
